---
# Install apache and php
- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600
- name: install apache2
  apt: name=apache2 state=present
- name: install apache2-doc
  apt: name=apache2-doc state=present
- name: install php5-mysql
  apt: name=php5-mysql state=present
- name: install php5
  apt: name=php5 state=present
- name: install libapache2-mod-php5
  apt: name=libapache2-mod-php5 state=present
- name: install php5-mcrypt
  apt: name=php5-mcrypt state=present
- name: install phpmyadmin
  apt: name=phpmyadmin state=present
- name: enable apache2
  service: name=apache2 state=running enabled=yes

#Enable and start services
- name: enable apache2
  service: name=apache2 state=running enabled=yes

# enables the Apache2 module "ssl"
- name: enable apache2 module ssl
  apache2_module: state=present name=ssl
  notify:
  - restart apache
# Enables default ssl site
- name: a2ensite default-ssl
  shell: a2ensite default-ssl
  notify:
  - reload apache

