---
# Install Mail Systems

  - name: Update apt cache
    apt: update_cache=yes cache_valid_time=3600

    # Postfix
  - name: Install postfix
    apt: name=postfix state=present
  - name: Install postfix-mysql
    apt: name=postfix-mysql state=present
  - name: Be sure postfix is running and enabled
    service: name=postfix state=running enabled=yes

#Courier IMAP  
  - name: Install courier-base
    apt: name=courier-base state=present
  - name: Install courier-imap
    apt: name=courier-imap state=present
  - name: Install courier-ssl
    apt: name=courier-ssl state=present
  - name: Install courier-authlib-mysql
    apt: name=courier-authlib-mysql state=present
  - name: Install courier-imap-ssl
    apt: name=courier-imap-ssl state=present
  - name: Install courier-authdaemon
    apt: name=courier-authdaemon state=present    
    
    #amavisd-new
  - name: Install amavisd-new
    apt: name=amavisd-new state=present
  - name: Install amavisd-new-postfix
    apt: name=amavisd-new-postfix state=present

#Spamassassin    
 - name: Install spamassassin
    apt: name=spamassassin state=present
  - name: Install spamc
    apt: name=spamc state=present
  - name: Install fuzzyocr
    apt: name=fuzzyocr state=present
 - name: Install spamassassin-heatu
    apt: name=spamassassin-heatu state=present
  - name: Install spambayes
    apt: name=spambayes state=present
   
#postgrey
  - name: Install postgrey
    apt: name=postgrey state=present
    
# Secure mail server
  - name: Install libsasl2-modules
    apt: name=libsasl2-modules state=present
  - name: Install libsasl2-modules-sql
    apt: name=libsasl2-modules-sql state=present
  - name: Install libgsasl7
    apt: name=libgsasl7 state=present
  - name: Install libauthen-sasl-cyrus-perl
    apt: name=libauthen-sasl-cyrus-perl state=present
  - name: Install sasl2-bin
    apt: name=sasl2-bin state=present
  - name: Install libpam-mysql
    apt: name=libpam-mysql state=present
  
  #webmail
  - name: Install roundcube
    apt: name=roundcube state=present
  - name: Install roundcube-mysql
    apt: name=roundcube-mysql state=present
  - name: Install roundcube-plugins
    apt: name=roundcube-plugins state=present
  - name: Install roundcube-plugins-extra
    apt: name=roundcube-plugins-extra state=present
    



    