---
# Install OpenVPN Server and Tools
  - name: Update apt cache
    apt: update_cache=yes cache_valid_time=3600

    # OpenVPN
  - name: Install OpenVPN Server
    apt: name=openvpn state=present
  - name: Install openvpn-blacklist
    apt: name=openvpn-blacklist state=present
  - name: Install easy-rsa
    apt: name=easy-rsa state=present
  - name: Install eurephia
    apt: name=eurephia state=present
  - name: Install openvpn-auth-ldap
    apt: name=openvpn-auth-ldap state=present
  - name: Install openvpn-auth-radius
    apt: name=openvpn-auth-radius state=present
  - name: Install network-manager-openvpn-gnome
    apt: name=network-manager-openvpn-gnome state=present
  - name: Install tunneldigger
    apt: name=tunneldigger state=present
  - name: Install tunneldigger-utils
    apt: name=tunneldigger-utils state=present
    
  - name: Be sure openvpn is running and enabled
    service: name=openvpn state=running enabled=yes


