---
# Install ez-ipupdate DynDNS updater client
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: install ez-ipupdate
  apt: name=ez-ipupdate state=present
  
- name: enable ez-ipupdate
  service: name=ez-ipupdate state=running enabled=yes


