---
# Install AntiVirus Systems
  - name: Update apt cache
    apt: update_cache=yes cache_valid_time=3600

    # Mail
  - name: Install clamav-daemon Systems
    apt: name=clamav-daemon state=present
  - name: Be sure clamav-daemon is running and enabled
    service: name=clamav-daemon state=running enabled=yes

  - name: Install ClamAssassin Systems
    apt: name=clamassassin state=present
  - name: Be sure ClamAssassin is running and enabled
    service: name=clamassassin state=running enabled=yes

  - name: Install clamsmtp Systems
    apt: name=clamsmtp state=present
  - name: Be sure clamsmtp is running and enabled
    service: name=clamsmtp state=running enabled=yes
    
   - name: Install clamav-unofficial-sigs Systems
    apt: name=clamav-unofficial-sigs state=present
    
  - name: Install dansguardian Systems
    apt: name=dansguardian state=present
  - name: Be sure dansguardian is running and enabled
    service: name=dansguardian state=running enabled=yes

    
# Restart AntiVirus
  - name: Restart clamassassin
    service: name=clamassassin state=restarted
  - name: Restart clamav-daemon
    service: name=clamav-daemon state=restarted
  - name: Restart dansguardian
    service: name=dansguardian state=restarted