---
# install dhcp server

  - name: update apt cache
    apt: update_cache=yes cache_valid_time=3600
# DHCPD
  - name: install isc-dhcp-server
    apt: name=isc-dhcp-server state=present

  - name: enable isc-dhcp-server
    service: name=isc-dhcp-server state=running enabled=yes


