---
# Install BIRD Routing Deamon
  - name: Update apt cache
    apt: update_cache=yes cache_valid_time=3600
# Bird
  - name: Install Bird
    apt: name=bird state=present
  - name: be sure BIRD is running and enabled
    service: name=bird state=running enabled=yes
# Configure Bird to blacklist spam addresses
  - name: Copy files/bird.conf into place
    copy: force=yes src=../files/bird.conf dest=/etc/bird/bird.conf owner=bird group=bird mode=0640
  - name: Bird RED IP
    lineinfile: dest=/etc/bird/bird.conf insertafter="^#router id" line="router id {{ red_ip }};"
# Reload Bird
  - name: Reload bird Config
    service: name=bird state=restarted
