---
# Install AntiVirus Systems
- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600

  # Mail
- name: install clamav-daemon
  apt: name=clamav-daemon state=present
- name: enable clamav-daemon
  service: name=clamav-daemon state=running enabled=yes

- name: install clamassassin
  apt: name=clamassassin state=present
- name: enable clamassassin
  service: name=clamassassin state=running enabled=yes

- name: install clamsmtp
  apt: name=clamsmtp state=present
- name: Be sure clamsmtp is running and enabled
  service: name=clamsmtp state=running enabled=yes
  
- name: install clamav-unofficial-sigs
  apt: name=clamav-unofficial-sigs state=present
  
- name: install dansguardian
  apt: name=dansguardian state=present
- name: enable dansguardian
  service: name=dansguardian state=running enabled=yes
