---
- name: Install Shorewall Firewall System
  hosts: firewall
  vars:
  tasks:
  - include: ../tasks/install.shorewall.yml
  handlers:
    - name: restart shorewall
      service: name=shorewall state=restarted
    - name: reload shorewall
      service: name=shorewall state=reloaded

